# vi: set ft=ruby ts=2 :

require 'yaml'

VAGRANTFILE_API_VERSION = "2"

# check for required plugins
_required_plugins_list = %w{vagrant-libvirt}
exit(1) unless _required_plugins_list.all? do |plugin|
  Vagrant.has_plugin?(plugin) || (
    STDERR.puts "Required plugin '#{plugin}' is missing; please install using:"
    STDERR.puts "  % vagrant plugin install #{plugin}"
    false
  )
end

# ensure libvirt is the default provider in case the vagrant box config
# doesn't specify it
ENV['VAGRANT_DEFAULT_PROVIDER'] = "libvirt"

@root_dir = File.dirname(File.expand_path(__FILE__))
@settings = YAML.load_file(File.join(@root_dir, "settings.yml"))

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # containerd is taking more than 60 seconds to shutdown in SUSE platforms
  # so increase the timeout to 120 seconds
  config.vm.graceful_halt_timeout = 120
  
  # PXE Server
  config.vm.define :pxe_server do |pxe_server|
    # https://portal.cloud.hashicorp.com/vagrant/discover/generic/
    pxe_server.vm.box = 'generic/debian12'
    pxe_server_vm_box_version = '4.3.12'

    # Vagrant < 2.3.0 does not handle multi-architecture metadata properly on Vagrant Cloud
    # and erroneously selects the ppc64le libvirt box on x86_64 systems (e.g. on openSUSE Leap 15.6).
    # Note: If an incorrect box was previously cached, remove it first:
    #   vagrant box remove generic/debian12 --provider libvirt
    if Gem::Version.new(Vagrant::VERSION) < Gem::Version.new('2.3.0')
      # When using a direct .box URL, do not specify box_version, otherwise Vagrant
      # aborts with a version constraint error (BoxAddDirectVersion).
      pxe_server.vm.box_url = "https://vagrantcloud.com/generic/boxes/debian12/versions/#{pxe_server_vm_box_version}/providers/libvirt/amd64/vagrant.box"
    else
      pxe_server.vm.box_version = pxe_server_vm_box_version
    end

    pxe_server.vm.hostname = 'pxe-server'
    pxe_server.vm.network 'private_network',
      ip: @settings['harvester_network_config']['dhcp_server']['ip'],
      libvirt__network_name: 'harvester',
      # don't enable DHCP as this node will have it's now DHCP server for iPXE
      libvirt__dhcp_enabled: false

    pxe_server.vm.provider :libvirt do |libvirt|
      libvirt.cpu_mode = 'host-passthrough'

      # If S3 backup target is enabled, allocate a little more CPU and memory
      # and create a suitable storage volume
      if @settings['s3']['enabled']
        libvirt.memory = '4096'
        libvirt.cpus = '2'
        libvirt.storage :file,
          size: @settings['s3']['capacity'],
          type: 'qcow2',
          bus: 'virtio',
          device: 'vdb'
      else
        libvirt.memory = '1024'
        libvirt.cpus = '1'
      end
    end

    pxe_server.vm.provision :ansible do |ansible|
      ansible.playbook = 'ansible/setup_pxe_server.yml'
      ansible.extra_vars = {
        settings: @settings
      }
    end
  end

  # Harvester
  cluster_node_index = @settings['harvester_cluster_nodes'] - 1
  (0..cluster_node_index).each do |node_number|
    vm_name = "harvester-node-#{node_number}"
    config.vm.define vm_name, autostart: false do |harvester_node|
      harvester_node.vm.hostname = "harvester-node-#{node_number}"
      harvester_node.vm.network 'private_network',
        libvirt__network_name: 'harvester',
        mac: @settings['harvester_network_config']['cluster'][node_number]['mgmt_mac']

      harvester_node.ssh.host = "#{@settings['harvester_network_config']['cluster'][node_number]['ip']}"
      harvester_node.ssh.username = "rancher"

      harvester_node.vm.provider :libvirt do |libvirt|
        libvirt.qemu_use_agent = true
        libvirt.mgmt_attach = false
        libvirt.cpu_mode = 'host-passthrough'
        libvirt.memory = @settings['harvester_network_config']['cluster'][node_number].key?('memory') ? @settings['harvester_network_config']['cluster'][node_number]['memory'] : @settings['harvester_node_config']['memory'] 
        libvirt.cpus = @settings['harvester_network_config']['cluster'][node_number].key?('cpu') ? @settings['harvester_network_config']['cluster'][node_number]['cpu'] : @settings['harvester_node_config']['cpu']
        libvirt.storage :file,
          size: @settings['harvester_network_config']['cluster'][node_number].key?('disk_size') ? @settings['harvester_network_config']['cluster'][node_number]['disk_size'] : @settings['harvester_node_config']['disk_size'],
          type: 'qcow2',
          bus: 'virtio',
          device: 'vda'
        boot_network = {'network' => 'harvester'}
        libvirt.boot 'hd'
        libvirt.boot boot_network

        os_release = `cat /etc/os-release`.downcase
        loader_path = if os_release.include?("ubuntu")
            "/usr/share/qemu/OVMF.fd"
        else
            "/usr/share/qemu/ovmf-x86_64.bin"
        end
        # NOTE: default to UEFI boot. Comment this out for legacy BIOS.
        libvirt.loader = loader_path
        libvirt.nic_model_type = 'e1000'
      end
    end
  end

  # Rancher
  if @settings['rancher_config']['enabled']
    config.vm.define :rancher do |rancher|
      rancher.vm.box = 'generic/debian10'
      rancher.vm.hostname = 'rancher'
      rancher.vm.network 'private_network',
        ip: @settings['rancher_config']['ip'],
        libvirt__network_name: 'harvester',
        libvirt__dhcp_enabled: false

        rancher.vm.provider :libvirt do |libvirt|
        libvirt.cpu_mode = 'host-passthrough'
        libvirt.cpus = @settings['rancher_config']['cpu']
        libvirt.memory = @settings['rancher_config']['memory']
      end

      rancher.vm.provision :ansible do |ansible|
        ansible.playbook = 'ansible/setup_rancher.yml'
        ansible.extra_vars = {
          settings: @settings
        }
      end
    end
  end

end
